language: node_js
node_js: lts/*

branches:
  only:
  - master
  - dev
  # Tags
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: "gjVMwgXkdvevQ5ahQNXi8AwOm+uaQH+cCzfgmA+90gyPxR6zAz3M1VmqcLmGw5Z5B4hH4QRf63+BquNVFJJrDFqrBocN797T/JGodLD6fVLDdkiEzeEnif3ukdfCjrJmNTE+pmAfdxsFfqcdLjiHy575w8silJvH69f74nS8lG7TUoyp8z/5dwmluOTH0pS+eEJgwzzGoQ29d9+XOXSm2V0ygJRVZzFLLNhb21Kqxx7on+pzeONFYovmm/+N6hZbnj7qsPbK58+Ke2eXGGKShd19zDuI7o4T8H2L0jTC97pW4JkvvEoZDUs74JPO/bUJdg+cA4ffakRE9RLtn5EmM3x8jNGu6ThdZn8OKY984Pfe5pviAwVoXZgAYekeGHwK6f5pH79rBH4hBEnPczBRTz0JXGeGSyvZrSLX5cGkaFkBWeM4z8dPE/qFkrl5KjONPDtrNuBczqCN8Bn2PTvnDBYRwTeAa22c8jTSeJtqWcS8TLOs97VD5+xh22EaxEDXPAih5xlAYqWaSAD9qoxgST+/iikrGj95epzVxYaiJxAZKCw29nGvOOrg2AHNUUntC0ActoIL5vdWtLMhtygDOPoPhIjKiVD8ayFdh1ylHl8V51nkRRHGsYjis1hOSAyYGhxvTOFExuKb3RWrMkxR1Icf5mKD/rZmWMexCFXz5CU="
  - secure: "mDznAndvuR5/+L3vXSKKgKJyxoZQR5tdeYzhG5Z0xltjz2cFqErLuUlJwTRiksSUzxWxtQL+cHytBo3KtLH1k3YipZhJWQ94seSLmia5jYDz5cYTPlmzPR7DmFvrFZqkXozc8LN9jOxC1cVVvy3VqBWFHzSgNvx6DU3Ntm4gxtYICyu/b81qsPtAlPguVtanz2J0m+kJ/eHtttjE2Spg+Q+L3CMYzry48s/UIMzZADoMLSuMRQmkhRyFzmaE8C3S9Qop5JZI0H8yb7VUJhIPH9dgEXGeuSRY98XHSylGL2g8h2Tsi5x5il+fIskVkERkKqaBkKLMz7dPNdTS/alqELYZlBvz6dj2OV//Q90mfT1kiQ6fMVqjQ6q67rb1C600K7vyBx6FpWyf+RuifRM+zsx+Qzg/lnb26BWIn+QvpaZFZcE8oiPTh8YTb7kv9gonUx3mFGUKDfEvIcP+XqLvZa7loqBluo6jYUmXwMVByVYa4f7QqNTMASo6KrjqtWSkAGtnUNFFCPYfj2lh6CPTb4acdx7el5ACVAClctmLLBMJ6w7VSz62YqHIKgA9aXXlyGm8z+JpCV2jEnRV/FT/vUK0ucGtYe0oHb+xxe428knI9Skh5C73kmzp52mnwzfNlkh8sc6AzVZw0kpEUaVYbcLLQGBlndI9ClUSZqzwNlA="

addons:
  apt:
    packages:
    - xvfb

install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm ci || npm install

script: skip

jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
