language: node_js
node_js: lts/*

branches:
  only:
  - master
  - dev
  # Tags
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: o12e5ETiBOaaH0xR0DLxxniiAeHwmLP9V4y/0njaj177BMxp5ic3p44La0vIikthH5REUgUe9Jedto8muBByu+QGxxXt53qzts9c78C4NIy9yVNt/jAX4nTrfAsNJy+FW+HIttg/4SALAC+pmicJGacvREhCd6e4+MM3pP4WiUuEhICgNRbtE9FuInemNt5DoB2jLH+eKInl18XfKNFxOAiPEJjqGJ6rnI1fSdc8K4LH20D4A9ZlqObLFR4ySGjPRcbIxDv0EtkteVy848GbUqyE6mkSNKlyZ3w3gKnTYAH4WJfAjkz78kMhcBY462SFQQdW+ndAosPMCuZ4/qxCo7wJXjj9Yi6Hzz4psnRrYgiMGQYOUr2NcBgFuKW27NuJbS0urkWWRsprmVb6T6iQ6Zynx/jaus4kWMX8aX8CAbXy5iUZ40iboxgWQy90gY/27AQVw8O5tftYT57oXWum63LwS8QgGaTqA9EIOa+kbAe5pt8ybhhCKOulv1YdFpsK1rHbBW6WBIcqqp7VLumABNPAbDSiHtTJFVmKEwY38iaAcbLgXzog+fyBLbUUeCP3ZXIt/JgH0HwO86a6zmF2tIpkohr5/3zbg0kFCc30Ii9luCAWvF6h9y+RxkSXbOgYFuO+tWYjoPTy57c9DYV7jEpkKlAj0k7FRa/Bx2cfF28=
  - secure: ati6t7dYjQTP7TyLUkTp2hpMFNuFnS52yHgC+xZ1IaLYek1N2ipvePy3hCU0QehiFR4P8pPFjhkExlzeyuzLbWy/xc+48xx7zdrlLxDLMjcCIZd8v7V2dWF6TOmhukbnwUULBFIfQjh4L1CHYtN6k46pcaMTgq1GSkQ04j7Nni3pZ644vqVt1Yck3ZEU6hBETmSn1DWZt0c2zfIP39BPS1u+oiGdQdjTUnYYR2l2icDIu1GvzLrKO9mt2HpSxEvX26u3PPMKnp1GjzKQBed4ECUrkWPFb+gbVtTaq2T0mGeX73xN/IDNvhRiBhXqf7j21n7uNdquA+JFSWmrF5RNpAgUVP/Vd3YrUiqst2ELQaC14h4rO9R1/L3ABdMYQD/XbBil+fkBD0Hb4LfmF6ZgLZk3RY2K4mzCg1BXmrwufNiCVqFD0KMLV+vUeyr2gRM/nq88hG169QonyMaFv3X184+zVa5jgvZV4ZLN6j312/xEv69X9I2H7rFdayXvUsVSbRmwDwHHoYHnmA4PKyNjiRXn8rLPA/mqZ59BpY2+dhZqN1O4fILAAsWYDMJxFRHg+HZenmWQHTXnjRMCvqEwi/hDYL5jKuNwmd4Bky8ZEnbDuZ4ai5LINUvCUSemPMMma3wxnCE+qirzWXFwVYVvQsaRBWiU72fnu00hW8qW28E=

addons:
  apt:
    packages:
    - xvfb

install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- npm ci || npm install

script: skip

jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
